### ISSUE TITLE
请问该文档是否是基于 5.0 版本？

### ISSUE THREAD

**Issue by XuJinNet** [zhangchen915/rx-book-cn#1]
感谢提供中文翻译版本！
请问该文档是否是基于 ReactiveX 5.0 版本？

**Comment by zhangchen915** [comment]
原文是4.0，不过我想要在翻译过程中升级到5.0
[rx4与rx5的区别](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md)

**Comment by XuJinNet** [comment]
谢谢 👍
